void findSegment(const uint8_t *target, const uint32_t target_len, void (*callback)(uint8_t *), int image_num);
void findSegment(const uint8_t *target, const uint32_t target_len, void (*callback)(uint8_t *));
void findSegmentForDyldImage(const uint8_t *target, const uint32_t target_len, void (*callback)(uint8_t *));
uint8_t *findS(const uint8_t *target);
uint8_t *findSA(const uint8_t *target);
void findSegment2ForDyldImage(const uint64_t *target, const uint64_t *mask, const uint32_t target_len, void (*callback)(uint8_t *), int image_num);
void findSegment2(const uint64_t *target, const uint64_t *mask, const uint32_t target_len, void (*callback)(uint8_t *));
bool patchCode(void *target, const void *data, size_t size);
void removeSYS_access();
void removeSYS_access2();
void removeSYS_open();
void removeSYS_symlink();
void remove1();
void remove2();
void remove3();
void remove4();
void remove5();
void remove6();
void remove7();
void _hookSymbol(void *hook);
void hookSymbol(const char *string);
void hookSymbolWithDLSYM(const char *string);
void hookSymbolWithDLSYMImage(const char *string, const char *image);
void _hookSymbol0(void *hook);
void hookSymbol0(const char *string);
void hookSymbol0WithDLSYM(const char *string);
void _hookSymbol1(void *hook);
void hookSymbol1WithDLSYMImage(const char *string, const char *image);
void hookSymbol1WithPrivateImage(const char *string, const char *image);
void hookingSVC80();
void hookingSVC80_NC();
void hookingAccessSVC80();